"""add_session_duration_and_pause

Revision ID: 0e5ae4c55511
Revises: 'e510a21b3557'
Create Date: 2026-08-05 19:08:01.216928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5ae4c55511'
down_revision: Union[str, None] = 'e510a21b3557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('current_question_duration', sa.Integer(), nullable=True))
    op.add_column('game_sessions', sa.Column('pause_started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_sessions', 'pause_started_at')
    op.drop_column('game_sessions', 'current_question_duration')
    # ### end Alembic commands ###
