"""add_assessment_and_attempts

Revision ID: 54c5ce613363
Revises: 'ff13774d943e'
Create Date: 2026-07-25 10:35:08.501131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c5ce613363'
down_revision: Union[str, None] = 'ff13774d943e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('question_analytics', sa.JSON(), nullable=True),
    sa.Column('randomized_question_ids', sa.JSON(), nullable=True),
    sa.Column('randomized_option_ids', sa.JSON(), nullable=True),
    sa.Column('tab_switch_count', sa.Integer(), nullable=False),
    sa.Column('fullscreen_exit_count', sa.Integer(), nullable=False),
    sa.Column('copy_paste_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_id'), 'quiz_attempts', ['id'], unique=False)
    op.add_column('quizzes', sa.Column('available_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quizzes', sa.Column('available_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quizzes', sa.Column('result_visibility', sa.String(length=50), server_default="immediate", nullable=False))
    op.add_column('quizzes', sa.Column('show_score', sa.Boolean(), server_default="1", nullable=False))
    op.add_column('quizzes', sa.Column('show_answers', sa.Boolean(), server_default="1", nullable=False))
    op.add_column('quizzes', sa.Column('show_explanations', sa.Boolean(), server_default="1", nullable=False))
    op.add_column('quizzes', sa.Column('show_solutions', sa.Boolean(), server_default="1", nullable=False))
    op.add_column('quizzes', sa.Column('show_marks', sa.Boolean(), server_default="1", nullable=False))
    op.add_column('quizzes', sa.Column('shuffle_questions', sa.Boolean(), server_default="0", nullable=False))
    op.add_column('quizzes', sa.Column('shuffle_options', sa.Boolean(), server_default="0", nullable=False))
    op.add_column('quizzes', sa.Column('access_code', sa.String(length=50), nullable=True))
    op.add_column('quizzes', sa.Column('custom_instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'custom_instructions')
    op.drop_column('quizzes', 'access_code')
    op.drop_column('quizzes', 'shuffle_options')
    op.drop_column('quizzes', 'shuffle_questions')
    op.drop_column('quizzes', 'show_marks')
    op.drop_column('quizzes', 'show_solutions')
    op.drop_column('quizzes', 'show_explanations')
    op.drop_column('quizzes', 'show_answers')
    op.drop_column('quizzes', 'show_score')
    op.drop_column('quizzes', 'result_visibility')
    op.drop_column('quizzes', 'available_until')
    op.drop_column('quizzes', 'available_from')
    op.drop_index(op.f('ix_quiz_attempts_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    # ### end Alembic commands ###
