"""extend_game_session

Revision ID: 5b2120be3967
Revises: 'd24cbe84920a'
Create Date: 2026-08-02 17:18:56.537879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2120be3967'
down_revision: Union[str, None] = 'd24cbe84920a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('require_host_to_start', sa.Boolean(), nullable=False))
    op.add_column('game_sessions', sa.Column('leaderboard_mode', sa.String(length=50), nullable=False))
    op.add_column('game_sessions', sa.Column('quiz_end_mode', sa.String(length=50), nullable=False))
    op.add_column('game_sessions', sa.Column('correct_answer_visibility', sa.String(length=50), nullable=False))
    op.add_column('game_sessions', sa.Column('question_navigation_mode', sa.String(length=50), nullable=False))
    op.add_column('game_sessions', sa.Column('question_order', sa.String(length=50), nullable=False))
    op.add_column('game_sessions', sa.Column('option_order', sa.String(length=50), nullable=False))
    op.add_column('game_sessions', sa.Column('late_join_policy', sa.String(length=50), nullable=False))
    op.add_column('game_sessions', sa.Column('is_paused', sa.Boolean(), nullable=False))
    op.add_column('game_sessions', sa.Column('answers_locked', sa.Boolean(), nullable=False))
    op.add_column('game_sessions', sa.Column('current_question_index', sa.Integer(), nullable=False))
    op.add_column('game_sessions', sa.Column('current_question_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('game_sessions', sa.Column('current_question_end_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_sessions', 'current_question_end_time')
    op.drop_column('game_sessions', 'current_question_started_at')
    op.drop_column('game_sessions', 'current_question_index')
    op.drop_column('game_sessions', 'answers_locked')
    op.drop_column('game_sessions', 'is_paused')
    op.drop_column('game_sessions', 'late_join_policy')
    op.drop_column('game_sessions', 'option_order')
    op.drop_column('game_sessions', 'question_order')
    op.drop_column('game_sessions', 'question_navigation_mode')
    op.drop_column('game_sessions', 'correct_answer_visibility')
    op.drop_column('game_sessions', 'quiz_end_mode')
    op.drop_column('game_sessions', 'leaderboard_mode')
    op.drop_column('game_sessions', 'require_host_to_start')
    # ### end Alembic commands ###
