"""add_quiz_timer_and_question_order

Revision ID: 9efb3a2422eb
Revises: '0bafcea8ee5e'
Create Date: 2026-07-25 09:43:38.238038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9efb3a2422eb'
down_revision: Union[str, None] = '0bafcea8ee5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('order_index', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('questions', sa.Column('time_limit_seconds', sa.Integer(), nullable=True))
    op.add_column('quizzes', sa.Column('timer_mode', sa.String(length=50), nullable=False, server_default='none'))
    op.add_column('quizzes', sa.Column('overall_time_limit_seconds', sa.Integer(), nullable=True))
    op.add_column('quizzes', sa.Column('auto_submit_on_expiry', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'auto_submit_on_expiry')
    op.drop_column('quizzes', 'overall_time_limit_seconds')
    op.drop_column('quizzes', 'timer_mode')
    op.drop_column('questions', 'time_limit_seconds')
    op.drop_column('questions', 'order_index')
    # ### end Alembic commands ###
