"""add_question_timer_override

Revision ID: c66936c0a630
Revises: '5b2120be3967'
Create Date: 2026-08-05 14:27:37.984800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66936c0a630'
down_revision: Union[str, None] = '5b2120be3967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('question_timer_override', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_quizzes_created_by_id'), table_name='quizzes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_quizzes_created_by_id'), 'quizzes', ['created_by_id'], unique=False)
    op.drop_column('game_sessions', 'question_timer_override')
    # ### end Alembic commands ###
