"""add_connection_token

Revision ID: e510a21b3557
Revises: 'c66936c0a630'
Create Date: 2026-08-05 17:57:51.315189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e510a21b3557'
down_revision: Union[str, None] = 'c66936c0a630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('connection_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'connection_token')
    # ### end Alembic commands ###
