"""add_ai_metadata_columns

Revision ID: ff13774d943e
Revises: '9efb3a2422eb'
Create Date: 2026-07-25 09:55:55.809438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff13774d943e'
down_revision: Union[str, None] = '9efb3a2422eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('course_outcome', sa.String(length=100), nullable=True))
    op.add_column('questions', sa.Column('reference', sa.String(length=255), nullable=True))
    op.add_column('questions', sa.Column('ai_provider', sa.String(length=50), nullable=True))
    op.add_column('questions', sa.Column('ai_model', sa.String(length=100), nullable=True))
    op.add_column('questions', sa.Column('generated_by_ai', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('questions', sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quizzes', sa.Column('ai_provider', sa.String(length=50), nullable=True))
    op.add_column('quizzes', sa.Column('ai_model', sa.String(length=100), nullable=True))
    op.add_column('quizzes', sa.Column('generation_prompt', sa.Text(), nullable=True))
    op.add_column('quizzes', sa.Column('generated_by_ai', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('quizzes', sa.Column('generation_source', sa.String(length=100), nullable=True))
    op.add_column('quizzes', sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'generated_at')
    op.drop_column('quizzes', 'generation_source')
    op.drop_column('quizzes', 'generated_by_ai')
    op.drop_column('quizzes', 'generation_prompt')
    op.drop_column('quizzes', 'ai_model')
    op.drop_column('quizzes', 'ai_provider')
    op.drop_column('questions', 'generated_at')
    op.drop_column('questions', 'generated_by_ai')
    op.drop_column('questions', 'ai_model')
    op.drop_column('questions', 'ai_provider')
    op.drop_column('questions', 'reference')
    op.drop_column('questions', 'course_outcome')
    # ### end Alembic commands ###
